# reid_system/config.yml

system:
  device: "cuda"
  # Las rutas apuntan a /app/data porque así montaremos el volumen en Docker
  cache_dir: "/app/data/features_cache"
  catalog_dir: "/app/data/Catalogo_PM"
  csv_path: "/app/data/Catalogo_PM.csv"

database:
  collection_name: "catalogo_pm_en_color_p3"

models:
  dinov2:
    repo: "facebookresearch/dinov2"
    name: "dinov2_vitl14" #  "dinov2_vitb14" or "dinov2_vitl14" 
    image_size: 518
    vector_size: 1024 # DINOv2-B14 tiene 768 dimensiones, DINOv2-L14 tiene 1024
    use_square_pad: true # Si es true, se mantendrá el aspect ratio original
  qwen:
    id: "Qwen/Qwen3-VL-Embedding-2B"
    max_image_size: 4096
    vector_size: 2048
    # 🚀 Prompt táctico extraído del código
    prompt: "Generate a discriminative embedding for this Mexican retail SKU. Prioritize: 1) Brand name and logo, 2) Specific flavor or aroma variant, 3) Exact net content and unit of measure, 4) Presence of nutritional warning labels (octagons), 5) Distinctive graphic elements on the packaging, and 6) Predominant color. Ignore the shelf context and lighting variations. Context: {metadata_text}"
    context:
      reference: "Reference retail product packaging from official catalog."
      query: "Query retail product packaging from store shelf."
  local_features:
    type: "superpoint"  # Opciones soportadas: "aliked", "superpoint", "dedode"
    max_num_keypoints: 2048
    detection_threshold: 0.2 # Usado por ALIKED y SuperPoint
    max_image_size: 4096
    preprocess:
      use_clahe: false

pipeline:
  retrieval:
    top_k: 40
    # 🚀 NUEVO: Modo de búsqueda. Opciones: "fusion", "dinov2_only", "qwen_only"
    search_mode: "qwen_only"
    # 🚀 NUEVO: Configuración del Re-Ranking K-Recíproco
    re_ranking:
      enabled: false
      k1: 10              # Tamaño del vecindario para buscar reciprocidad
      lambda_weight: 0.3  # Peso entre Jaccard (0.7) y Distancia Original (0.3)
  verification:
    min_matches_lightglue: 10
    ransac_threshold: 4.0
    min_inliers_valid: 14

video_processor:
  model_name: "product_gondola_yolov26m_v01.pt"
  tracker_config: "retail_tracker.yaml"
  tracking:
    max_unseen_frames: 120
    min_trajectory_frames: 40
  geometry:
    edge_margin_pct: 0.05
    focus_band_top_pct: 0.25
    focus_band_bottom_pct: 0.75
    min_height_pct: 0.05
  filters:
    min_box_width: 30
    min_box_height: 30
  detector:
    confidence_threshold: 0.1
    iou_threshold: 0.7
    imgsz: 1024
  clustering:
    dbscan_eps: 15.0
    min_samples: 2
    deep_similarity_threshold: 0.75